# fly.toml app configuration file
app = "go-blog"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[http_service.tls]
alpn = ["h2", "h3"]

[checks]
[checks.alive]
type = "tcp"
interval = "15s"
timeout = "2s"
grace_period = "5s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024